name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    env:
       app_name: app_${RUNNER_OS}_ver.${GITHUB_RUN_NUMBER}
    steps:
      - uses: actions/checkout@v3
      - name: build hello world
        run: |
          g++ main.cpp -o ${{ env.app_name }}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: my_app
          path: app_**
          petention-days: 1
          
  build_macos:
    runs-on: macos-latest
    env:
       app_name: app_${RUNNER_OS}_ver.${GITHUB_RUN_NUMBER}
    steps:
      - uses: actions/checkout@v3
      - name: build hello world
        run: |
          g++ main.cpp -o ${{ env.app_name }}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: my_app
          path: app_**
          petention-days: 1
          
  build_win:
    runs-on: windows-latest
    env:
       app_name: app_${RUNNER_OS}_ver.${GITHUB_RUN_NUMBER}
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1.10.0
      - name: build hello world
        run: |
            cl /EHsc main.cpp
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: my_app
          path: main.exe
          petention-days: 1
